version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-laravel-roadmap-backend
    container_name: php-laravel-roadmap-backend
    restart: unless-stopped

    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: host.docker.internal

    working_dir: /var/www/html
    # This service still runs php-fpm by default (no override). 
    expose:
      - "9000"

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"   # Host port 8080 → container port 80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
