services:
  php-laravel-roadmap-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-laravel-roadmap-backend
    container_name: php-laravel-roadmap-backend
    restart: unless-stopped

    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal

    # ─────────────────────────────────────────────────────────────
    # on first start (no vendor/), bootstrap Laravel, then run php-fpm
    command: >
      sh -c "
        if [ ! -d vendor ]; then
          composer install --no-interaction --prefer-dist --optimize-autoloader &&
          php artisan key:generate &&
          php artisan migrate --force
        fi &&
        php-fpm
      "
    # ─────────────────────────────────────────────────────────────

    expose:
      - "9000"

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"   # Host port 8080 → container port 80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-laravel-roadmap-backend
